server:
  port: 2121
  ssl:
    key-store: ${KEY_STORE_PATH}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-alias: ${KEY_AS}


cors:
  origins: ${CORS_ORIGINS}

upload:
  image:
    dir: ${UPLOAD_IMAGE_DIR}
    path: ${UPLOAD_IMAGE_PATH}
    url: ${UPLOAD_IMAGE_URL}